### ISSUE TITLE
Add Dark Theme

### ISSUE THREAD

**Issue by sanket143** [sinix-dev/sinix-mobile#36]
A PR can be for any of the following unchecked components.

**Subtasks**
- [x] Add `darkTheme` in `ThemeData` [75 points]
- [ ] Joystick page [75 points]
- [x] Joystick edit page [75 points]
- [x] Available Devices [25 points]
- [x] Onboarding Page [75 points]

**Colour Values**
`#223346`
`#FFFFFF`
`#FFFFFF`: `35% opacity`
`#152438`: `95% opacity` (For Text)

![Android - 5](https://user-images.githubusercontent.com/26973649/98069328-7e650c80-1e84-11eb-9b21-0421e05eb9e9.png)
![Android - 6](https://user-images.githubusercontent.com/26973649/98069538-09460700-1e85-11eb-979e-a7466727915d.png)
![Android - 8](https://user-images.githubusercontent.com/26973649/98069571-1cf16d80-1e85-11eb-9259-fd42d953dd35.png)

**Comment by GajjarMiten** [comment]
I would like to work on this :)

**Comment by sanket143** [comment]
Sure, you can mention the component you want to work on here. We can't assign the whole issue to you.

**Comment by GajjarMiten** [comment]
Sure I will make pr for joystick page.

**Comment by ritvij14** [comment]
I will work on the onboarding page.
